/**
 * Simplified DE postal prefix → state/region for manual fallback (prototype).
 * Production may use a full PLZ database.
 */
const PREFIX_TO_REGION: Record<string, string> = {
  "66": "Saarland",
  "67": "Rhineland-Palatinate",
  "68": "Rhineland-Palatinate",
  "69": "Rhineland-Palatinate",
  "70": "Baden-Württemberg",
  "71": "Baden-Württemberg",
  "72": "Baden-Württemberg",
  "73": "Baden-Württemberg",
  "74": "Baden-Württemberg",
  "75": "Baden-Württemberg",
  "76": "Baden-Württemberg",
  "77": "Baden-Württemberg",
  "78": "Baden-Württemberg",
  "79": "Baden-Württemberg",
  "80": "Bavaria",
  "81": "Bavaria",
  "82": "Bavaria",
  "83": "Bavaria",
  "84": "Bavaria",
  "85": "Bavaria",
  "86": "Bavaria",
  "87": "Bavaria",
  "88": "Bavaria",
  "89": "Bavaria",
  "90": "Bavaria",
  "91": "Bavaria",
  "92": "Bavaria",
  "93": "Bavaria",
  "94": "Bavaria",
  "95": "Bavaria",
  "96": "Bavaria",
  "97": "Bavaria",
  "20": "Hamburg",
  "21": "Hamburg",
  "22": "Hamburg",
  "23": "Hamburg",
  "24": "Schleswig-Holstein",
  "25": "Schleswig-Holstein",
  "26": "Schleswig-Holstein",
  "27": "Schleswig-Holstein",
  "28": "Bremen",
  "29": "Bremen",
  "30": "Lower Saxony",
  "31": "Lower Saxony",
  "32": "Lower Saxony",
  "33": "Lower Saxony",
  "34": "Lower Saxony",
  "35": "Lower Saxony",
  "36": "Lower Saxony",
  "37": "Lower Saxony",
  "38": "Lower Saxony",
  "39": "Lower Saxony",
  "40": "NRW",
  "41": "NRW",
  "42": "NRW",
  "43": "NRW",
  "44": "NRW",
  "45": "NRW",
  "46": "NRW",
  "47": "NRW",
  "48": "NRW",
  "49": "NRW",
  "50": "NRW",
  "51": "NRW",
  "52": "NRW",
  "53": "NRW",
  "54": "NRW",
  "55": "NRW",
  "56": "NRW",
  "57": "NRW",
  "58": "NRW",
  "59": "NRW",
  "60": "Hesse",
  "61": "Hesse",
  "62": "Hesse",
  "63": "Hesse",
  "64": "Hesse",
  "65": "Hesse",
  "10": "Berlin",
  "11": "Berlin",
  "12": "Berlin",
  "13": "Berlin",
  "14": "Brandenburg",
  "15": "Brandenburg",
  "16": "Brandenburg",
  "17": "Mecklenburg-Vorpommern",
  "18": "Mecklenburg-Vorpommern",
  "19": "Mecklenburg-Vorpommern",
  "01": "Saxony",
  "02": "Saxony",
  "03": "Saxony",
  "04": "Saxony",
  "06": "Saxony-Anhalt",
  "07": "Saxony-Anhalt",
  "08": "Saxony-Anhalt",
  "09": "Saxony-Anhalt",
  "98": "Thuringia",
  "99": "Thuringia",
};

export function regionFromPostalInput(input: string): string | null {
  const digits = input.replace(/\D/g, "");
  if (digits.length < 2) return null;
  const prefix = digits.slice(0, 2);
  return PREFIX_TO_REGION[prefix] ?? null;
}
